{"event":"runStart","testCount":"72","fuzzRuns":"100","globs":[],"paths":["C:\\Users\\Adrianc\\Desktop\\PF\\PROIECT\\proj\\tests\\ExampleTests\\CursorTests.elm","C:\\Users\\Adrianc\\Desktop\\PF\\PROIECT\\proj\\tests\\ExampleTests\\ModelPostIdsTests.elm","C:\\Users\\Adrianc\\Desktop\\PF\\PROIECT\\proj\\tests\\ExampleTests\\ModelPostsConfigTests.elm","C:\\Users\\Adrianc\\Desktop\\PF\\PROIECT\\proj\\tests\\ExampleTests\\UtilTimeTests.elm","C:\\Users\\Adrianc\\Desktop\\PF\\PROIECT\\proj\\tests\\MainTests.elm","C:\\Users\\Adrianc\\Desktop\\PF\\PROIECT\\proj\\tests\\PostsConfigTests.elm","C:\\Users\\Adrianc\\Desktop\\PF\\PROIECT\\proj\\tests\\PostsViewTests.elm","C:\\Users\\Adrianc\\Desktop\\PF\\PROIECT\\proj\\tests\\PostTests.elm","C:\\Users\\Adrianc\\Desktop\\PF\\PROIECT\\proj\\tests\\SimulatedEffect.elm","C:\\Users\\Adrianc\\Desktop\\PF\\PROIECT\\proj\\tests\\TestData.elm","C:\\Users\\Adrianc\\Desktop\\PF\\PROIECT\\proj\\tests\\TestUtils.elm"],"initialSeed":"376158560164992"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.CursorTests","module Cursor","back","#back: \n\n    nonEmpty 1 [ 2, 3 ] |> forward |> Maybe.andThen back\n    --> Just (withSelectedElement [] 1 [2, 3])"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 82\n\nforward\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 82\n\nforward\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"2"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.CursorTests","module Cursor","back","#back: \n\n    back (nonEmpty 1 [])\n    --> Nothing"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 99\n\nback\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 99\n\nback\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.CursorTests","module Cursor","back","#back: \n\n    back (nonEmpty 1 [ 2, 3 ])\n    --> Nothing"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 99\n\nback\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 99\n\nback\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"2"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.CursorTests","module Cursor","forward","#forward: \n\n    nonEmpty 1 [ 2, 3 ] |> forward |> Maybe.andThen forward\n    --> Just (withSelectedElement [1, 2] 3 [])"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 82\n\nforward\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 82\n\nforward\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.CursorTests","module Cursor","forward","#forward: \n\n    forward (nonEmpty 1 [])\n    --> Nothing"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 82\n\nforward\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 82\n\nforward\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.CursorTests","module Cursor","forward","#forward: \n\n    forward (nonEmpty 1 [ 2, 3 ])\n    --> Just (withSelectedElement [1] 2 [3])"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 82\n\nforward\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 82\n\nforward\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.CursorTests","module Cursor","fromList","#fromList: \n\n    fromList []\n    --> Nothing"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 40\n\nfromList\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 40\n\nfromList\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.CursorTests","module Cursor","fromList","#fromList: \n\n    fromList [ 1, 2, 3 ]\n    --> Just (withSelectedElement [] 1 [2, 3])"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 40\n\nfromList\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 40\n\nfromList\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.CursorTests","module Cursor","length","#length: \n\n    length (nonEmpty 1 [ 2, 3 ])\n    --> 3"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 112\n\nlength\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 112\n\nlength\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.CursorTests","module Cursor","length","#length: \n\n    length (nonEmpty 1 [])\n    --> 1"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 112\n\nlength\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 112\n\nlength\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.CursorTests","module Cursor","toList","#toList: \n\n    toList (nonEmpty 1 [ 2, 3 ])\n    --> [1, 2, 3]"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 51\n\ntoList\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Cursor` on line 51\n\ntoList\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.ModelPostIdsTests","module Model.PostIds","advance","#advance: \n\n    advance (PostIds (Cursor.withSelectedElement [ 1, 2 ] 3 []))\n    --> Nothing"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostIds` on line 64\n\nadvance\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostIds` on line 64\n\nadvance\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.ModelPostIdsTests","module Model.PostIds","advance","#advance: \n\n    advance (PostIds (Cursor.nonEmpty 1 [ 2, 3 ]))\n    --> Just ( 2, PostIds (Cursor.withSelectedElement [1] 2 [3]))"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostIds` on line 64\n\nadvance\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostIds` on line 64\n\nadvance\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.ModelPostIdsTests","module Model.PostIds","decode","#decode: \n\n    De.decodeString decode \"[]\"\n    --> Ok (Nothing)"],"failures":[{"given":null,"message":"Expect.equal","reason":{"type":"Equality","data":{"expected":"Err (Failure \"TODO\" <internals>)","actual":"Ok Nothing","comparison":"Expect.equal"}}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.ModelPostIdsTests","module Model.PostIds","decode","#decode: \n\n    De.decodeString decode \"[1]\"\n    --> Ok (Just (PostIds (Cursor.nonEmpty 1 [])))"],"failures":[{"given":null,"message":"Expect.equal","reason":{"type":"Equality","data":{"expected":"Err (Failure \"TODO\" <internals>)","actual":"Ok (Just (PostIds (Cursor [] 1 [])))","comparison":"Expect.equal"}}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.ModelPostIdsTests","module Model.PostIds","decode","#decode: \n\n    De.decodeString decode \"[1, 2, 3]\"\n    --> Ok (Just (PostIds (Cursor.nonEmpty 1 [2, 3])))"],"failures":[{"given":null,"message":"Expect.equal","reason":{"type":"Equality","data":{"expected":"Err (Failure \"TODO\" <internals>)","actual":"Ok (Just (PostIds (Cursor [] 1 [2,3])))","comparison":"Expect.equal"}}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.ModelPostsConfigTests","module Model.PostsConfig","sortFromString","#sortFromString: \n\n    sortFromString \"Title\"\n    --> Just Title"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 48\n\nsortFromString\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 48\n\nsortFromString\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.ModelPostsConfigTests","module Model.PostsConfig","sortFromString","#sortFromString: \n\n    sortFromString \"Invalid\"\n    --> Nothing"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 48\n\nsortFromString\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 48\n\nsortFromString\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.ModelPostsConfigTests","module Model.PostsConfig","sortFromString","#sortFromString: \n\n    sortFromString \"Score\"\n    --> Just Score"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 48\n\nsortFromString\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 48\n\nsortFromString\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","durationBetween","#durationBetween: \n\n    durationBetween (Time.millisToPosix 1000) (Time.millisToPosix 1000)\n    --> Nothing"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","durationBetween","#durationBetween: \n\n    durationBetween (Time.millisToPosix 1000) (Time.millisToPosix 0)\n    --> Nothing"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","durationBetween","#durationBetween: \n\n    durationBetween (Time.millisToPosix 0) (Time.millisToPosix (4 * 24 * 60 * 60 * 1000 + 3 * 60 * 60 * 1000 + 2 * 60 * 1000 + 1000))\n    --> Just (Duration 1 2 3 4)"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","durationBetween","#durationBetween: \n\n    durationBetween (Time.millisToPosix 0) (Time.millisToPosix (24 * 60 * 60 * 1000 + 1000))\n    --> Just (Duration 1 0 0 1)"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","durationBetween","#durationBetween: \n\n    durationBetween (Time.millisToPosix 0) (Time.millisToPosix (24 * 60 * 60 * 1000))\n    --> Just (Duration 0 0 0 1)"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","durationBetween","#durationBetween: \n\n    durationBetween (Time.millisToPosix 0) (Time.millisToPosix (60 * 60 * 1000))\n    --> Just (Duration 0 0 1 0)"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","durationBetween","#durationBetween: \n\n    durationBetween (Time.millisToPosix 0) (Time.millisToPosix (60 * 1000))\n    --> Just (Duration 0 1 0 0)"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","durationBetween","#durationBetween: \n\n    durationBetween (Time.millisToPosix 0) (Time.millisToPosix (1000))\n    --> Just (Duration 1 0 0 0)"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 144\n\ndurationBetween\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","formatDuration","#formatDuration: \n\n    formatDuration (Duration 0 30 0 1)\n    --> \"1 day 30 minutes ago\""],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","formatDuration","#formatDuration: \n\n    formatDuration (Duration 0 47 6 2)\n    --> \"2 days 6 hours 47 minutes ago\""],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","formatDuration","#formatDuration: \n\n    formatDuration (Duration 0 1 1 1)\n    --> \"1 day 1 hour 1 minute ago\""],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","formatDuration","#formatDuration: \n\n    formatDuration (Duration 0 0 0 3)\n    --> \"3 days ago\""],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","formatDuration","#formatDuration: \n\n    formatDuration (Duration 0 0 2 0)\n    --> \"2 hours ago\""],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","formatDuration","#formatDuration: \n\n    formatDuration (Duration 0 1 0 0)\n    --> \"1 minute ago\""],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","formatDuration","#formatDuration: \n\n    formatDuration (Duration 2 0 0 0)\n    --> \"2 seconds ago\""],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["ExampleTests.UtilTimeTests","module Util.Time","formatDuration","#formatDuration: \n\n    formatDuration (Duration 1 0 0 0)\n    --> \"1 second ago\""],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Util.Time` on line 169\n\nformatDuration\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["MainTests","module Main","Main.update handles config update message","The ConfigChange message is sent when the \"Show job posts\" checkbox is clicked"],"failures":[{"given":null,"message":"ensureHttpRequest: Expected HTTP request (GET http://localhost:3000/v0/item/38144400.json) to have been made and still be pending, but no such requests were made.\n    No requests were made.","reason":{"type":"Custom","data":"ensureHttpRequest: Expected HTTP request (GET http://localhost:3000/v0/item/38144400.json) to have been made and still be pending, but no such requests were made.\n    No requests were made."}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"2"}
{"event":"testCompleted","status":"fail","labels":["MainTests","module Main","Main.update handles config update message","The ConfigChange message is sent when the \"Show text only posts\" checkbox is clicked"],"failures":[{"given":null,"message":"ensureHttpRequest: Expected HTTP request (GET http://localhost:3000/v0/item/38144400.json) to have been made and still be pending, but no such requests were made.\n    No requests were made.","reason":{"type":"Custom","data":"ensureHttpRequest: Expected HTTP request (GET http://localhost:3000/v0/item/38144400.json) to have been made and still be pending, but no such requests were made.\n    No requests were made."}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["MainTests","module Main","Main.update handles config update message","The ConfigChange message is sent when the \"Posts to show\" select is changed"],"failures":[{"given":null,"message":"ensureHttpRequest: Expected HTTP request (GET http://localhost:3000/v0/item/38144400.json) to have been made and still be pending, but no such requests were made.\n    No requests were made.","reason":{"type":"Custom","data":"ensureHttpRequest: Expected HTTP request (GET http://localhost:3000/v0/item/38144400.json) to have been made and still be pending, but no such requests were made.\n    No requests were made."}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["MainTests","module Main","Main.update handles config update message","The ConfigChange message is sent when the \"Sort by\" select is changed"],"failures":[{"given":null,"message":"ensureHttpRequest: Expected HTTP request (GET http://localhost:3000/v0/item/38144400.json) to have been made and still be pending, but no such requests were made.\n    No requests were made.","reason":{"type":"Custom","data":"ensureHttpRequest: Expected HTTP request (GET http://localhost:3000/v0/item/38144400.json) to have been made and still be pending, but no such requests were made.\n    No requests were made."}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["PostsConfigTests","module Model.PostsConfig","showTextOnly","text posts are removed when showTextOnly is False"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["PostsConfigTests","module Model.PostsConfig","showJobs","job posts are removed when showJobs is False"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsConfigTests","module Model.PostsConfig","postsToShow","the number of posts returned is at most postsToShow"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsConfigTests","module Model.PostsConfig","sortBy","The final list is not sorted when sortBy is None"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsConfigTests","module Model.PostsConfig","sortBy","The final list is sorted by title when sortBy is Title"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsConfigTests","module Model.PostsConfig","sortBy","The final list is sorted descending by score when sortBy is Score"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["PostsConfigTests","module Model.PostsConfig","applyChanges","The ConfigChange message is sent when the \"Show job posts\" checkbox is clicked"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsConfigTests","module Model.PostsConfig","applyChanges","The ConfigChange message is sent when the \"Show text only posts\" checkbox is clicked"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsConfigTests","module Model.PostsConfig","applyChanges","The ConfigChange message is sent when the \"Posts to show\" select is changed"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsConfigTests","module Model.PostsConfig","applyChanges","The ConfigChange message is sent when the \"Sort by\" select is changed"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","\"Show job posts\" checkbox","postsConfigView has a checkbox for \"Show job posts\""],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","\"Show text only posts\" checkbox","postsConfigView has a checkbox for \"Show text only posts\""],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","\"posts per page\" select","postsConfigView has a \"posts per page\" select input wiht 3 options"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","\"posts per page\" select","The options for \"posts per page\" select input are 10, 25, 50"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","\"sort by\" select","postsConfigView has a \"sort by\" select input with 4 options"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","\"sort by\" select","The options for \"sort by\" select input are Score, Title, Posted, None"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","postsConfigView update","The ConfigChange message is sent when the \"Show job posts\" checkbox is clicked"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","postsConfigView update","The ConfigChange message is sent when the \"Show text only posts\" checkbox is clicked"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","postsConfigView update","The ConfigChange message is sent when the \"Posts to show\" select is changed"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","postsConfigView update","The ConfigChange message is sent when the \"Sort by\" select is changed"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 53\n\npostsConfigView\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","postTable","View contains a table element"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","postTable","The table has 5 columns"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","first row","The first row of the table contains the field names"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","field tags","Each body row contains a cell with class post-score"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","field tags","Each body row contains a cell with class post-title"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","field tags","Each body row contains a cell with class post-type"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"3"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","field tags","Each body row contains a cell with class post-time"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","field tags","Each body row contains a cell with class post-url"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `View.Posts` on line 33\n\npostTable\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","field values","the number of rows is equal to the number of elements in the list"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","field values","each row contains all fields"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"1"}
{"event":"testCompleted","status":"fail","labels":["PostsViewTests","module View.Posts","uses relative time","the relative time is shown using a title attribute"],"failures":[{"given":null,"message":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\"","reason":{"type":"Custom","data":"This test failed because it threw an exception: \"Error: TODO in module `Model.PostsConfig` on line 108\n\nfilterPosts\""}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"fail","labels":["PostTests","module Post","Post.decode","decode parses post correctly"],"failures":[{"given":null,"message":"Expect.ok","reason":{"type":"Comparison","data":{"first":"Ok _","second":"Err (Failure \"TODO\" <internals>)","comparison":"Expect.ok"}}}],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"0"}
{"event":"testCompleted","status":"pass","labels":["PostTests","module Post","Post.decode","decode fails if a field is missing"],"failures":[],"distributionReports":[{"type":"NoDistribution","data":null}],"duration":"15"}
{"event":"runComplete","passed":"1","failed":"71","duration":"454","autoFail":null}
